Repository plentymarkets/terra-components, pull requests merged in 2018-11, with the labels that each got.

#729 Feature/3.0.0/data table context menu
  CHANGELOG.md
  src/app/components/tables/data-table/context-menu/data/terra-data-table-context-menu-entry.interface.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.html
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.directive.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.service.ts
  src/app/components/tables/data-table/example/terra-data-table.component.example.html
  src/app/components/tables/data-table/example/terra-data-table.component.example.ts
  src/app/components/tables/data-table/interfaces/terra-data-table-row.interface.ts
  src/app/components/tables/data-table/terra-data-table.component.html
  src/app/components/tables/data-table/terra-data-table.component.ts
Labels: Refactor, v3

#736 fix (data-table): error with undefined pagingSizes
  CHANGELOG.md
  src/app/components/pager/data/terra-pager-default-paging-sizes.ts
  src/app/components/pager/data/terra-pager.data.ts
  src/app/components/pager/terra-pager.component.ts
  src/app/components/tables/data-table/example/terra-data-table.service.example.ts
  src/app/components/tables/data-table/terra-data-table-base.service.ts
  src/index.ts
Labels: Fix, v3

#731 (terra-regex): remove getters - instead grant public access to the members
  CHANGELOG.md
  src/app/helpers/regex/terra-regex.ts
Labels: Refactor

#704 feature (data-table): redesign
  CHANGELOG.md
  src/app/components/buttons/button-with-options/terra-button-with-options.component.ts
  src/app/components/component-collection.ts
  src/app/components/directive-collection.ts
  src/app/components/example-collection.ts
  src/app/components/pager/data/terra-pager-default-paging-sizes.ts
  src/app/components/pager/data/terra-pager.data.ts
  src/app/components/pager/terra-pager.component.ts
  src/app/components/tables/data-table/cell/terra-ref-type.interface.ts
  src/app/components/tables/data-table/context-menu/data/terra-data-table-context-menu-entry.interface.ts
  src/app/components/tables/data-table/context-menu/directive/terra-data-table-context-menu.directive.ts
  src/app/components/tables/data-table/context-menu/service/terra-data-table-context-menu.service.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.html
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.directive.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.service.ts
  src/app/components/tables/data-table/enums/terra-data-table-sort-order.enum.ts
  src/app/components/tables/data-table/enums/terra-href-type.enum.ts
  src/app/components/tables/data-table/enums/terra-text-align.enum.ts
  src/app/components/tables/data-table/example/terra-data-table.component.example.html
  src/app/components/tables/data-table/example/terra-data-table.component.example.ts
  src/app/components/tables/data-table/example/terra-data-table.interface.example.ts
  src/app/components/tables/data-table/example/terra-data-table.service.example.ts
  src/app/components/tables/data-table/interfaces/terra-data-table-cell.interface.ts
  src/app/components/tables/data-table/interfaces/terra-data-table-header-cell.interface.ts
  src/app/components/tables/data-table/interfaces/terra-data-table-row.interface.ts
  src/app/components/tables/data-table/interfaces/terra-data-table-text.interface.ts
  src/app/components/tables/data-table/interfaces/terra-href-type.interface.ts
  src/app/components/tables/data-table/row/terra-data-table-row.interface.ts
  src/app/components/tables/data-table/terra-data-table-base.service.ts
  src/app/components/tables/data-table/terra-data-table.component.html
  src/app/components/tables/data-table/terra-data-table.component.scss
  src/app/components/tables/data-table/terra-data-table.component.spec.ts
  src/app/components/tables/data-table/terra-data-table.component.ts
  src/app/components/tables/group-function/example/terra-group-function.component.example.html
  src/app/components/tables/group-function/example/terra-group-function.component.example.ts
  src/app/components/tables/group-function/terra-group-function.component.html
  src/app/components/tables/group-function/terra-group-function.component.scss
  src/app/components/tables/group-function/terra-group-function.component.spec.ts
  src/app/components/tables/group-function/terra-group-function.component.ts
  src/app/components/tables/simple/cell/terra-simple-table-header-cell.interface.ts
  src/app/components/tables/terra-base-table.ts
  src/app/service/service-collection.ts
  src/app/terra-components.module.ts
  src/index.ts
Labels: Feature, Refactor, v3

#747 fix (simple-table): notifications via outputSelectedRowsChange
  CHANGELOG.md
  src/app/components/tables/simple/example/terra-simple-table.component.example.html
  src/app/components/tables/simple/example/terra-table-simple.component.example.ts
  src/app/components/tables/simple/terra-simple-table.component.ts
Labels: Fix

#718 Crm/remove stopwatch package and replace with own logic
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/components/stopwatch/example/terra-stopwatch.component.example.html
  src/app/components/stopwatch/example/terra-stopwatch.component.example.ts
  src/app/components/stopwatch/terra-stopwatch.component.html
  src/app/components/stopwatch/terra-stopwatch.component.spec.ts
  src/app/components/stopwatch/terra-stopwatch.component.ts
Labels: Refactor, security vulnerability
