Repository plentymarkets/terra-components, pull requests merged in 2018-06, with the labels that each got.

#412 Feature/timepicker
  CHANGELOG.md
  package.json
  src/app/assets/lang/locale-de.json
  src/app/assets/lang/locale-en.json
  src/app/components/forms/input/time-picker/example/terra-time-picker.component.example.html
  src/app/components/forms/input/time-picker/example/terra-time-picker.component.example.scss
  src/app/components/forms/input/time-picker/example/terra-time-picker.component.example.ts
  src/app/components/forms/input/time-picker/terra-time-picker.component.html
  src/app/components/forms/input/time-picker/terra-time-picker.component.scss
  src/app/components/forms/input/time-picker/terra-time-picker.component.ts
  src/app/terra-components.module.ts
  src/index.ts
Labels: Feature

#526 Updated component examples
  CHANGELOG.md
  src/app/components/buttons/button-with-options/example/terra-button-with-options.component.example.html
  src/app/components/editors/note-editor/example/terra-note-editor.component.example.html
  src/app/components/editors/note-editor/example/terra-note-editor.component.example.ts
  src/app/components/editors/syntax-editor/example/terra-syntax-editor.component.example.html
  src/app/components/editors/syntax-editor/example/terra-syntax-editor.component.example.ts
  src/app/components/filter/example/terra-filter.component.example.html
  src/app/components/filter/example/terra-filter.component.example.scss
  src/app/components/forms/input/color-picker/example/terra-color-picker.component.example.html
  src/app/components/forms/input/color-picker/example/terra-color-picker.component.example.ts
  src/app/components/layouts/card/example/terra-card.component.example.html
  src/app/components/layouts/info-box/example/terra-info-box.component.example.html
  src/app/components/layouts/info-box/example/terra-info-box.component.example.md
  src/app/components/layouts/info-box/example/terra-info-box.component.example.scss
  src/app/components/layouts/info-box/example/terra-info-box.component.example.ts
  src/app/components/layouts/tag/example/terra-tag.component.example.html
  src/app/components/layouts/tag/example/terra-tag.component.example.md
  src/app/components/layouts/tag/example/terra-tag.component.example.scss
  src/app/components/layouts/taglist/example/terra-taglist.component.example.html
  src/app/components/layouts/taglist/example/terra-taglist.component.example.ts
  src/app/components/note/example/terra-note.component.example.scss
  src/app/components/pager/example/terra-pager.component.example.scss
  src/app/components/tree/node-tree/example/terra-node-tree.component.example.scss
  src/app/terra-components.component.html
Labels: Fix

#522 Fix/file browser issues
  src/app/components/file-browser/file-list/file-list.component.scss
  src/app/components/file-browser/terra-frontend-storage.service.ts
Labels: Fix

#511 Feature/custom lint rules
  .gitignore
  gulp.config.js
  gulpfile.js
  lintRules/getSetRule.ts
  lintRules/maxDepthRule.ts
  lintRules/restrictLeadingUnderscoreRule.ts
  package-lock.json
  package.json
  src/app/components/pager/example/terra-pager.component.example.ts
  tslint-rules.json
  tslint.json
Labels: tslint

#551 fix (node tree): search
  CHANGELOG.md
  src/app/components/tree/node-tree/data/terra-node-tree.config.ts
  src/app/components/tree/node-tree/terra-node-tree.component.ts
Labels: Fix
