Repository plentymarkets/terra-components, pull requests merged in 2018-09, with the labels that each got.

#636 Fix/terra form child scope evaluation
  CHANGELOG.md
  src/app/components/forms/form/form-container/terra-form-container.component.ts
  src/app/components/forms/form/form-entry-list/terra-form-entry-list.component.ts
Labels: Fix

#637 updated karma to 3.0.0
  package-lock.json
  package.json
Labels: security vulnerability

#646 FIX member access modifier
  src/app/components/file-browser/file-list/file-list.component.html
  src/app/components/file-browser/file-list/file-list.component.ts
Labels: Fix

#647 Fixing a null pointer in the node tree
  CHANGELOG.md
  src/app/components/tree/node-tree/data/terra-node-tree.config.ts
Labels: Fix

#650 hotfix (suggestion-box): do not reset input text value when typing
  CHANGELOG.md
  src/app/components/forms/suggestion-box/example/terra-suggestion-box.component.example.ts
  src/app/components/forms/suggestion-box/terra-suggestion-box.component.ts
Labels: Hotfix
