Repository plentymarkets/terra-components, pull requests merged in 2018-03, with the labels that each got.

#420 Ignore .d.ts-files in src folder when compiling ts
  gulp.config.js
Labels: Fix

#462 fix (security vulnerability): update moment
  package-lock.json
  package.json
Labels: security vulnerability

#464 updated changelog
  CHANGELOG.md
Labels: Fix

#465 feature (models): key-value interfaces
  src/app/models/terra-key-value-pair.interface.ts
  src/app/models/terra-key-value.interface.ts
Labels: Feature

#481 FIX style
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.html
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.ts
Labels: Fix

#473 Fix/dynamic form portlet
  CHANGELOG.md
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.html
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.ts
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.html
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.ts
  src/app/components/layouts/portlet/terra-portlet.component.html
Labels: Fix

#469 Feature/content builder
  CHANGELOG.md
  src/app/components/category-picker/config/category-tree.config.ts
  src/app/components/category-picker/data/category-pager-data.interface.ts
  src/app/components/category-picker/data/category-value.interface.ts
  src/app/components/category-picker/terra-category-picker.component.html
  src/app/components/category-picker/terra-category-picker.component.ts
  src/app/components/forms/dynamic-form/data/terra-form-field-color-picker.ts
  src/app/components/forms/dynamic-form/data/terra-form-field-input-file.ts
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.html
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.ts
  src/app/components/forms/dynamic-form/enum/terra-control-type.enum.ts
  src/app/components/forms/dynamic-form/handler/terra-dynamic-form-functions.handler.ts
  src/app/components/forms/dynamic-form/service/terra-form-field-control.service.ts
  src/app/components/forms/dynamic-form/service/terra-json-to-form-field.service.ts
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.html
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.scss
  src/app/components/forms/dynamic-form/terra-dynamic-form.component.ts
  src/app/components/forms/input/text-input/terra-text-input.component.ts
  src/app/components/forms/multi-check-box/terra-multi-check-box.component.spec.ts
  src/app/components/pager/data/terra-pager.data.ts
  src/app/components/tree/node-tree/data/terra-node.interface.ts
  src/app/components/tree/node-tree/node/terra-node.component.html
  src/app/components/tree/node-tree/node/terra-node.component.ts
  src/app/components/tree/node-tree/terra-node-tree.component.html
  src/app/components/tree/node-tree/terra-node-tree.component.scss
  src/app/service/terra-base.service.ts
  src/app/terra-components.module.ts
  src/index.ts
Labels: Feature
