Repository plentymarkets/terra-components, pull requests merged in 2018-04, with the labels that each got.

#492 FIX location of helper classes
  src/app/components/file-browser/file-list/file-list.component.ts
  src/app/components/file-browser/model/terra-storage-object.ts
  src/app/components/file-browser/model/terra-upload-item.ts
  src/app/components/forms/input/file-input/terra-file-input.component.ts
  src/app/helpers/clipboard.helper.ts
  src/app/helpers/enums/index.ts
  src/app/helpers/fileType.helper.ts
  src/app/helpers/index.ts
  src/app/helpers/path.helper.ts
  src/app/helpers/regex/index.ts
  src/index.ts
Labels: Refactor

#498 feature/category_picker_buttons
  src/app/components/category-picker/terra-category-picker.component.html
Labels: Feature

#475 ADD display progress when uploading files
  package.json
  src/app/assets/lang/locale-de.json
  src/app/assets/lang/locale-en.json
  src/app/components/file-browser/file-list/file-list.component.html
  src/app/components/file-browser/file-list/file-list.component.scss
  src/app/components/file-browser/file-list/file-list.component.ts
  src/app/components/file-browser/model/terra-upload-progress.ts
  src/app/components/file-browser/model/terra-upload-queue.ts
Labels: Feature

#497 Fix/dynamic form container
  CHANGELOG.md
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.html
  src/app/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.scss
Labels: Fix

#404 feature (build): prerelease versions
  gulpfile.js
Labels: Feature

#500 add array-type rule with fixed files from fixer
  src/app/components/buttons/file-chooser/terra-file-chooser.component.ts
  src/app/components/file-browser/file-list/file-list.component.ts
  src/app/components/file-browser/model/terra-storage-object-list.ts
  src/app/components/file-browser/model/terra-storage-object.ts
  src/app/components/file-browser/model/terra-upload-item.ts
  src/app/components/file-browser/terra-base-storage.interface.ts
  src/app/components/file-browser/terra-frontend-storage.service.ts
  src/app/components/filter/terra-filter.component.ts
  src/app/components/forms/input/file-input/terra-file-input.component.ts
  src/app/components/forms/slider/terra-slider.component.ts
  src/app/components/tables/data-table/context-menu/service/terra-data-table-context-menu.service.ts
  src/app/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
  src/app/helpers/path.helper.ts
  tslint-rules.json
Labels: tslint
