Repository plentymarkets/terra-components, pull requests merged in 2019-02, with the labels that each got.

#834 fix(checkbox-group): null value handling
  CHANGELOG.md
  src/app/components/forms/checkbox-group/checkbox-group.component.spec.ts
  src/app/components/forms/checkbox-group/checkbox-group.component.ts
  src/app/components/forms/multi-check-box/terra-multi-check-box.component.ts
Labels: Fix, Patch

#835 added tooltip for checkbox
  CHANGELOG.md
  src/app/components/buttons/button/terra-button.component.ts
  src/app/components/forms/checkbox/example/terra-checkbox.component.example.html
  src/app/components/forms/checkbox/terra-checkbox.component.html
  src/app/components/forms/checkbox/terra-checkbox.component.scss
  src/app/components/forms/checkbox/terra-checkbox.component.ts
Labels: Minor change

#847 FIX change detection when changing an array value
  CHANGELOG.md
  src/app/components/forms/form/form-entry/terra-form-entry.component.ts
Labels: Fix
