Repository plentymarkets/terra-components, pull requests merged in 2019-05, with the labels that each got.

#900 fix(security): update dependencies
  package-lock.json
  package.json
Labels: security vulnerability

#886 Feature (Radio-Group): Remove the select filter in ng-content
  CHANGELOG.md
  src/app/components/forms/input/radio/example/radio-group.component.example.html
  src/app/components/forms/input/radio/example/radio-group.component.example.ts
  src/app/components/forms/input/radio/radio-group.component.html
Labels: Feature

#890 FIX breadcrumbs
  CHANGELOG.md
  src/app/components/breadcrumbs/service/terra-breadcrumbs.service.ts
Labels: Fix
