Repository plentymarkets/terra-components, pull requests merged in 2019-07, with the labels that each got.

#947 CHANGE html-linter.helper.ts - fix import of htmlhint
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Hotfix

#962 UPDATE package-lock.json
  package-lock.json
  package.json
Labels: security vulnerability

#967 fix(component-collection): duplicate export category picker
  src/lib/components/component-collection.ts
Labels: Fix, Patch

#966 Added: Option to color select box items
  CHANGELOG.md
  src/lib/components/forms/select-box/data/allowed.colors.enum.ts
  src/lib/components/forms/select-box/data/terra-select-box.interface.ts
  src/lib/components/forms/select-box/example/terra-select-box.component.example.html
  src/lib/components/forms/select-box/example/terra-select-box.component.example.ts
  src/lib/components/forms/select-box/terra-select-box.component.html
  src/lib/components/forms/select-box/terra-select-box.component.spec.ts
  src/lib/public-api.ts
Labels: Feature, Minor change

#969 Transform file extensions to lowercase for easier comparisons
  CHANGELOG.md
  src/lib/helpers/path.helper.ts
  src/lib/helpers/tests/path.helper.spec.ts
Labels: Fix, Patch
