Repository plentymarkets/terra-components, pull requests merged in 2019-03, with the labels that each got.

#858 fix (date picker): endless loop for early dates
  CHANGELOG.md
  src/app/components/forms/input/date-picker/example/terra-date-picker.component.example.html
  src/app/components/forms/input/date-picker/example/terra-date-picker.component.example.ts
  src/app/components/forms/input/date-picker/terra-date-picker.component.html
  src/app/components/forms/input/date-picker/terra-date-picker.component.ts
Labels: Fix, Minor change

#843 fix(card): vertical card alignment
  CHANGELOG.md
  src/app/components/layouts/card/terra-card.component.html
  src/app/components/layouts/card/terra-card.component.scss
  src/app/components/layouts/card/terra-card.component.spec.ts
  src/app/components/layouts/card/terra-card.component.ts
Labels: Fix, Patch

#831 feature(base-service): change typdef of dataId parameter in caching methods
  CHANGELOG.md
  src/app/service/terra-base.service.ts
Labels: Feature, Minor change

#820 feature(terra-form): add support for validation via reactive forms
  CHANGELOG.md
  src/app/components/forms/form/form-container/terra-form-container.component.html
  src/app/components/forms/form/form-container/terra-form-container.component.ts
  src/app/components/forms/form/form-entry-list/terra-form-entry-list.component.html
  src/app/components/forms/form/form-entry-list/terra-form-entry-list.component.ts
  src/app/components/forms/form/form-entry/terra-form-entry.component.html
  src/app/components/forms/form/form-entry/terra-form-entry.component.ts
  src/app/components/forms/form/helper/terra-form-field.helper.ts
  src/app/components/forms/form/terra-form.component.ts
Labels: Feature

#852 Added: Tooltip for code editor
  CHANGELOG.md
  src/app/components/editors/base-editor/terra-base-editor.component.ts
  src/app/components/editors/code-editor/example/terra-code-editor.component.example.html
  src/app/components/editors/code-editor/terra-code-editor.component.html
  src/app/components/editors/code-editor/terra-code-editor.component.scss
Labels: Feature
