Repository plentymarkets/terra-components, pull requests merged in 2020-04, with the labels that each got.

#979 feature(loading-spinner): notify parent windows about the loading status...
  CHANGELOG.md
  src/lib/components/alert/alert.service.spec.ts
  src/lib/components/alert/alert.service.ts
  src/lib/components/loading-spinner/service/terra-loading-spinner.service.spec.ts
  src/lib/components/loading-spinner/service/terra-loading-spinner.service.ts
  src/lib/utils/index.ts
  src/lib/utils/window.ts
Labels: Feature, Minor change

#1165 fix(security vulnerabilities): update packages
  package-lock.json
Labels: security vulnerability

#1172 FIX (portlet): overflow
  CHANGELOG.md
  src/lib/components/layouts/portlet/terra-portlet.component.scss
Labels: Fix
