Repository plentymarkets/terra-components, pull requests merged in 2020-08, with the labels that each got.

#1315 feature(prettier): apply prettier to src/lib/component/layouts/info-box
  src/lib/components/layouts/info-box/example/terra-info-box.component.example.html
  src/lib/components/layouts/info-box/example/terra-info-box.component.example.md
  src/lib/components/layouts/info-box/example/terra-info-box.component.example.ts
  src/lib/components/layouts/info-box/terra-info-box.component.html
  src/lib/components/layouts/info-box/terra-info-box.component.scss
  src/lib/components/layouts/info-box/terra-info-box.component.spec.ts
  src/lib/components/layouts/info-box/terra-info-box.component.ts
Labels: Feature, prettier

#1314 feature(prettier): apply prettier to src/lib/component/layouts/column-container
  src/lib/components/layouts/column-container/column-container.config.ts
  src/lib/components/layouts/column-container/three-columns/example/terra-three-column-container.component.example.html
  src/lib/components/layouts/column-container/three-columns/example/terra-three-column-container.component.example.ts
  src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.scss
  src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.spec.ts
  src/lib/components/layouts/column-container/three-columns/terra-three-columns-container.component.ts
  src/lib/components/layouts/column-container/two-columns/example/terra-two-column-container.component.example.ts
  src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.scss
  src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.spec.ts
  src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.component.ts
  src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.directive.spec.ts
  src/lib/components/layouts/column-container/two-columns/terra-two-columns-container.directive.ts
Labels: Feature, prettier

#1313 feature(prettier): apply prettier to src/lib/component/layouts/card
  src/lib/components/layouts/card/example/terra-card.component.example.html
  src/lib/components/layouts/card/example/terra-card.component.example.ts
  src/lib/components/layouts/card/terra-card.component.html
  src/lib/components/layouts/card/terra-card.component.scss
  src/lib/components/layouts/card/terra-card.component.spec.ts
  src/lib/components/layouts/card/terra-card.component.ts
Labels: Feature, prettier

#1311 feature(prettier): apply prettier to src/lib/component/info
  src/lib/components/info/example/terra-info.component.example.html
  src/lib/components/info/example/terra-info.component.example.scss
  src/lib/components/info/example/terra-info.component.example.ts
  src/lib/components/info/terra-info.component.html
  src/lib/components/info/terra-info.component.scss
  src/lib/components/info/terra-info.component.spec.ts
  src/lib/components/info/terra-info.component.ts
Labels: Feature, prettier

#1310 feature(prettier): apply prettier to src/lib/component/indicator
  src/lib/components/indicator/terra-indicator.component.html
  src/lib/components/indicator/terra-indicator.component.scss
  src/lib/components/indicator/terra-indicator.component.spec.ts
  src/lib/components/indicator/terra-indicator.component.ts
Labels: Feature, prettier

#1278 feature(prettier): apply prettier to src/lib/components/forms
  src/lib/components/forms/terra-forms.example.html
  src/lib/components/forms/terra-forms.example.ts
Labels: Feature, prettier

#1277 feature(prettier): apply prettier to src/lib/components/forms/tag-select
  src/lib/components/forms/tag-select/example/terra-tag-select.component.example.ts
  src/lib/components/forms/tag-select/terra-tag-select.component.html
  src/lib/components/forms/tag-select/terra-tag-select.component.scss
  src/lib/components/forms/tag-select/terra-tag-select.component.ts
Labels: Feature, prettier

#1276 feature(prettier): apply prettier to src/lib/components/forms/suggestion-box
  src/lib/components/forms/suggestion-box/data/terra-suggestion-box.interface.ts
  src/lib/components/forms/suggestion-box/example/terra-suggestion-box.component.example.html
  src/lib/components/forms/suggestion-box/example/terra-suggestion-box.component.example.ts
  src/lib/components/forms/suggestion-box/terra-suggestion-box.component.html
  src/lib/components/forms/suggestion-box/terra-suggestion-box.component.scss
  src/lib/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts
  src/lib/components/forms/suggestion-box/terra-suggestion-box.component.ts
Labels: Feature, prettier

#1275 feature(prettier): apply prettier to src/lib/components/forms/slider
  src/lib/components/forms/slider/data/terra-slider-tick.ts
  src/lib/components/forms/slider/example/terra-slider.component.example.html
  src/lib/components/forms/slider/example/terra-slider.component.example.ts
  src/lib/components/forms/slider/terra-slider.component.html
  src/lib/components/forms/slider/terra-slider.component.scss
  src/lib/components/forms/slider/terra-slider.component.spec.ts
  src/lib/components/forms/slider/terra-slider.component.ts
Labels: Feature, prettier

#1274 feature(prettier): apply prettier to src/lib/components/forms/select-box
  src/lib/components/forms/select-box/data/allowed.colors.enum.ts
  src/lib/components/forms/select-box/data/terra-select-box.interface.ts
  src/lib/components/forms/select-box/directive/select-sort.directive.spec.ts
  src/lib/components/forms/select-box/directive/select-sort.directive.ts
  src/lib/components/forms/select-box/example/terra-select-box.component.example.html
  src/lib/components/forms/select-box/example/terra-select-box.component.example.ts
  src/lib/components/forms/select-box/terra-select-box.component.html
  src/lib/components/forms/select-box/terra-select-box.component.scss
  src/lib/components/forms/select-box/terra-select-box.component.spec.ts
  src/lib/components/forms/select-box/terra-select-box.component.ts
Labels: Feature, prettier

#1273 feature(prettier): apply prettier to src/lib/components/forms/radio-button
  src/lib/components/forms/radio-button/example/terra-radio-button.component.example.html
  src/lib/components/forms/radio-button/example/terra-radio-button.component.example.ts
  src/lib/components/forms/radio-button/terra-radio-button.component.html
  src/lib/components/forms/radio-button/terra-radio-button.component.scss
  src/lib/components/forms/radio-button/terra-radio-button.component.ts
Labels: Feature, prettier

#1272 feature(prettier): apply prettier to src/lib/components/forms/multi-checkbox
  src/lib/components/forms/multi-check-box/data/terra-multi-check-box-value.interface.ts
  src/lib/components/forms/multi-check-box/example/terra-multi-check-box.component.example.html
  src/lib/components/forms/multi-check-box/example/terra-multi-check-box.component.example.ts
  src/lib/components/forms/multi-check-box/terra-multi-check-box.component.html
  src/lib/components/forms/multi-check-box/terra-multi-check-box.component.scss
  src/lib/components/forms/multi-check-box/terra-multi-check-box.component.spec.ts
  src/lib/components/forms/multi-check-box/terra-multi-check-box.component.ts
Labels: Feature, prettier

#1270 feature(prettier): apply prettier to src/lib/components/forms/form
  src/lib/components/forms/form/example/form-fields.ts
  src/lib/components/forms/form/example/terra-form.component.example.html
  src/lib/components/forms/form/example/terra-form.component.example.ts
  src/lib/components/forms/form/form-container/container-wrapper/terra-form-container-wrapper.component.ts
  src/lib/components/forms/form/form-container/terra-form-container.component.html
  src/lib/components/forms/form/form-container/terra-form-container.component.scss
  src/lib/components/forms/form/form-container/terra-form-container.component.spec.ts
  src/lib/components/forms/form/form-container/terra-form-container.component.ts
  src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.html
  src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.scss
  src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.spec.ts
  src/lib/components/forms/form/form-entry-list/terra-form-entry-list.component.ts
  src/lib/components/forms/form/form-entry/form-entry-container.directive.ts
  src/lib/components/forms/form/form-entry/terra-form-entry.base.ts
  src/lib/components/forms/form/form-entry/terra-form-entry.component.ts
  src/lib/components/forms/form/helper/terra-form-field.helper.spec.ts
  src/lib/components/forms/form/helper/terra-form-field.helper.ts
  src/lib/components/forms/form/helper/terra-form.helper.spec.ts
  src/lib/components/forms/form/helper/terra-form.helper.ts
  src/lib/components/forms/form/model/form-type-map.ts
  src/lib/components/forms/form/model/terra-form-field.interface.ts
  src/lib/components/forms/form/model/terra-form-property.decorator.ts
  src/lib/components/forms/form/model/terra-form-scope.data.ts
  src/lib/components/forms/form/model/terra-form-type-map.enum.ts
  src/lib/components/forms/form/model/terra-form-type.interface.ts
  src/lib/components/forms/form/terra-form.component.html
  src/lib/components/forms/form/terra-form.component.scss
  src/lib/components/forms/form/terra-form.component.spec.ts
  src/lib/components/forms/form/terra-form.component.ts
Labels: Feature, prettier

#1269 feature(prettier): apply prettier to src/lib/components/forms/dynamic-form
  src/lib/components/forms/dynamic-form/data/terra-form-field-base-container.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-base.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-category-picker.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-check-box.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-code-editor.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-color-picker.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-date-picker.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-horizontal-container.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-input-double.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-input-file.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-input-number.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-input-text.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-multi-check-box.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-note-editor.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-select-box.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-text-area.ts
  src/lib/components/forms/dynamic-form/data/terra-form-field-vertical-container.ts
  src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.html
  src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.scss
  src/lib/components/forms/dynamic-form/dynamic-switch/terra-dynamic-switch.component.ts
  src/lib/components/forms/dynamic-form/enum/terra-control-type.enum.ts
  src/lib/components/forms/dynamic-form/handler/terra-dynamic-form-functions.handler.ts
  src/lib/components/forms/dynamic-form/service/terra-dynamic-form.service.ts
  src/lib/components/forms/dynamic-form/service/terra-form-field-control.service.ts
  src/lib/components/forms/dynamic-form/service/terra-json-to-form-field.service.ts
  src/lib/components/forms/dynamic-form/terra-dynamic-form.component.html
  src/lib/components/forms/dynamic-form/terra-dynamic-form.component.scss
  src/lib/components/forms/dynamic-form/terra-dynamic-form.component.ts
Labels: Feature, prettier

#1268 feature(prettier): apply prettier to src/lib/components/forms/checkbox-group
  src/lib/components/forms/checkbox-group/checkbox-group.component.html
  src/lib/components/forms/checkbox-group/checkbox-group.component.spec.ts
  src/lib/components/forms/checkbox-group/checkbox-group.component.ts
  src/lib/components/forms/checkbox-group/example/checkbox-group.component.example.html
  src/lib/components/forms/checkbox-group/example/checkbox-group.component.example.ts
Labels: Feature, prettier

#1312 feature(prettier): apply prettier to src/lib/component/interactables
  src/lib/components/interactables/draggable.directive.ts
  src/lib/components/interactables/draggableOptions.interface.ts
  src/lib/components/interactables/dropEvent.interface.ts
  src/lib/components/interactables/dropzone.directive.ts
  src/lib/components/interactables/gridOptions.interface.ts
  src/lib/components/interactables/inertiaOptions.interface.ts
  src/lib/components/interactables/interact.module.ts
  src/lib/components/interactables/interactableOptions.interface.ts
  src/lib/components/interactables/resizable.directive.ts
  src/lib/components/interactables/resizeOptions.interface.ts
  src/lib/components/interactables/restrictOptions.interface.ts
Labels: Feature, prettier

#1267 feature(prettier): apply prettier to src/lib/components/forms/checkbox
  src/lib/components/forms/checkbox/example/terra-checkbox.component.example.html
  src/lib/components/forms/checkbox/example/terra-checkbox.component.example.ts
  src/lib/components/forms/checkbox/terra-checkbox.component.html
  src/lib/components/forms/checkbox/terra-checkbox.component.scss
  src/lib/components/forms/checkbox/terra-checkbox.component.spec.ts
  src/lib/components/forms/checkbox/terra-checkbox.component.ts
Labels: Feature, prettier

#1261 feature(prettier): apply prettier to src/lib/components/filter
  src/lib/components/filter/example/filter.component.example.html
  src/lib/components/filter/example/filter.component.example.ts
  src/lib/components/filter/example/terra-filter.component.example.html
  src/lib/components/filter/example/terra-filter.component.example.ts
  src/lib/components/filter/filter.component.html
  src/lib/components/filter/filter.component.spec.ts
  src/lib/components/filter/filter.component.ts
  src/lib/components/filter/terra-filter.component.html
  src/lib/components/filter/terra-filter.component.ts
Labels: Feature, prettier

#1260 feature(prettier): apply prettier to src/lib/components/file-browser
  src/lib/components/file-browser/example/terra-file-browser.component.example.ts
  src/lib/components/file-browser/file-list/file-list.component.html
  src/lib/components/file-browser/file-list/file-list.component.scss
  src/lib/components/file-browser/file-list/file-list.component.ts
  src/lib/components/file-browser/image-preview/image-preview.component.html
  src/lib/components/file-browser/image-preview/image-preview.component.scss
  src/lib/components/file-browser/image-preview/image-preview.component.ts
  src/lib/components/file-browser/model/s3-storage-object.interface.ts
  src/lib/components/file-browser/model/terra-image-metadata.interface.ts
  src/lib/components/file-browser/model/terra-storage-object-list.ts
  src/lib/components/file-browser/model/terra-storage-object.ts
  src/lib/components/file-browser/model/terra-upload-item.ts
  src/lib/components/file-browser/model/terra-upload-progress.ts
  src/lib/components/file-browser/model/terra-upload-queue.ts
  src/lib/components/file-browser/terra-base-metadata-storage.interface.ts
  src/lib/components/file-browser/terra-base-private-storage.interface.ts
  src/lib/components/file-browser/terra-base-storage.interface.ts
  src/lib/components/file-browser/terra-file-browser.component.glob.scss
  src/lib/components/file-browser/terra-file-browser.component.html
  src/lib/components/file-browser/terra-file-browser.component.ts
  src/lib/components/file-browser/terra-file-browser.service.ts
  src/lib/components/file-browser/terra-frontend-storage.service.ts
Labels: Feature, prettier

#1259 feature(prettier): apply prettier to src/lib/components/editors
  src/lib/components/editors/base-editor/terra-base-editor.component.glob.scss
  src/lib/components/editors/base-editor/terra-base-editor.component.html
  src/lib/components/editors/base-editor/terra-base-editor.component.ts
  src/lib/components/editors/ck-editor/ck-editor-full.directive.spec.ts
  src/lib/components/editors/ck-editor/ck-editor.directive.ts
  src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.html
  src/lib/components/editors/ck-editor/example/ck-editor-directive-example.component.ts
  src/lib/components/editors/ck-editor/presets/ck-editor-full-preset.ts
  src/lib/components/editors/ck-editor/presets/ck-editor-minimum-preset.ts
  src/lib/components/editors/code-editor/example/terra-code-editor.component.example.html
  src/lib/components/editors/code-editor/example/terra-code-editor.component.example.scss
  src/lib/components/editors/code-editor/example/terra-code-editor.component.example.ts
  src/lib/components/editors/code-editor/helper/html-linter-message.interface.ts
  src/lib/components/editors/code-editor/helper/html-linter-rule.enum.ts
  src/lib/components/editors/code-editor/helper/html-linter.helper.ts
  src/lib/components/editors/code-editor/terra-code-editor.component.html
  src/lib/components/editors/code-editor/terra-code-editor.component.scss
  src/lib/components/editors/code-editor/terra-code-editor.component.spec.ts
  src/lib/components/editors/code-editor/terra-code-editor.component.ts
  src/lib/components/editors/note-editor/example/terra-note-editor.component.example.html
  src/lib/components/editors/note-editor/example/terra-note-editor.component.example.ts
  src/lib/components/editors/note-editor/terra-note-editor.component.html
  src/lib/components/editors/note-editor/terra-note-editor.component.ts
  src/lib/components/editors/syntax-editor/data/terra-syntax-editor.data.ts
  src/lib/components/editors/syntax-editor/example/terra-syntax-editor.component.example.html
  src/lib/components/editors/syntax-editor/example/terra-syntax-editor.component.example.ts
  src/lib/components/editors/syntax-editor/terra-syntax-editor.component.html
  src/lib/components/editors/syntax-editor/terra-syntax-editor.component.ts
Labels: Feature, prettier

#1243 feature(prettier): apply prettier to src/lib/components/buttons
  src/lib/components/buttons/button-with-options/example/terra-button-with-options.component.example.html
  src/lib/components/buttons/button-with-options/example/terra-button-with-options.component.example.ts
  src/lib/components/buttons/button-with-options/terra-button-with-options.component.html
  src/lib/components/buttons/button-with-options/terra-button-with-options.component.scss
  src/lib/components/buttons/button-with-options/terra-button-with-options.component.ts
  src/lib/components/buttons/button/data/terra-button.interface.ts
  src/lib/components/buttons/button/example/terra-button.component.example.html
  src/lib/components/buttons/button/example/terra-button.component.example.ts
  src/lib/components/buttons/button/terra-button.component.html
  src/lib/components/buttons/button/terra-button.component.scss
  src/lib/components/buttons/button/terra-button.component.ts
  src/lib/components/buttons/file-chooser/terra-file-chooser.component.html
  src/lib/components/buttons/file-chooser/terra-file-chooser.component.scss
  src/lib/components/buttons/file-chooser/terra-file-chooser.component.ts
  src/lib/components/buttons/toggle/example/terra-toggle.component.example.html
  src/lib/components/buttons/toggle/example/terra-toggle.component.example.ts
  src/lib/components/buttons/toggle/terra-toggle.component.html
  src/lib/components/buttons/toggle/terra-toggle.component.scss
  src/lib/components/buttons/toggle/terra-toggle.component.ts
Labels: Feature, prettier

#1242 feature(prettier): apply prettier to src/lib/components/breadcrumbs
  src/lib/components/breadcrumbs/service/terra-breadcrumbs.service.ts
  src/lib/components/breadcrumbs/terra-breadcrumb-container.ts
  src/lib/components/breadcrumbs/terra-breadcrumb.ts
  src/lib/components/breadcrumbs/terra-breadcrumbs.component.html
  src/lib/components/breadcrumbs/terra-breadcrumbs.component.scss
  src/lib/components/breadcrumbs/terra-breadcrumbs.component.ts
Labels: Feature, prettier

#1241 feature(prettier): apply prettier to src/lib/components/alert
  src/lib/components/alert/alert-type.enum.ts
  src/lib/components/alert/alert.service.spec.ts
  src/lib/components/alert/alert.service.ts
  src/lib/components/alert/data/terra-alert.interface.ts
  src/lib/components/alert/example/terra-alert.component.example.html
  src/lib/components/alert/example/terra-alert.component.example.ts
  src/lib/components/alert/terra-alert-panel.component.glob.scss
  src/lib/components/alert/terra-alert-panel.component.html
  src/lib/components/alert/terra-alert-panel.component.ts
  src/lib/components/alert/terra-alert.component.ts
Labels: Feature, prettier

#1320 feature(prettier): apply prettier to src/lib/component/layouts/overlay
  src/lib/components/layouts/overlay/data/terra-overlay-button.interface.ts
  src/lib/components/layouts/overlay/example/terra-overlay.component.example.html
  src/lib/components/layouts/overlay/example/terra-overlay.component.example.ts
  src/lib/components/layouts/overlay/terra-overlay.component.html
  src/lib/components/layouts/overlay/terra-overlay.component.scss
  src/lib/components/layouts/overlay/terra-overlay.component.spec.ts
  src/lib/components/layouts/overlay/terra-overlay.component.ts
Labels: Feature, prettier

#1321 feature(prettier): apply prettier to src/lib/component/layouts/portlet
  src/lib/components/layouts/portlet/example/terra-portlet.component.example.html
  src/lib/components/layouts/portlet/example/terra-portlet.component.example.ts
  src/lib/components/layouts/portlet/terra-portlet.component.html
  src/lib/components/layouts/portlet/terra-portlet.component.scss
  src/lib/components/layouts/portlet/terra-portlet.component.spec.ts
  src/lib/components/layouts/portlet/terra-portlet.component.ts
Labels: Feature, prettier

#1322 feature(prettier): apply prettier to src/lib/component/layouts/tag
  src/lib/components/layouts/tag/data/terra-tag-name.interface.ts
  src/lib/components/layouts/tag/data/terra-tag.interface.ts
  src/lib/components/layouts/tag/example/terra-tag.component.example.html
  src/lib/components/layouts/tag/example/terra-tag.component.example.md
  src/lib/components/layouts/tag/example/terra-tag.component.example.scss
  src/lib/components/layouts/tag/example/terra-tag.component.example.ts
  src/lib/components/layouts/tag/terra-tag.component.html
  src/lib/components/layouts/tag/terra-tag.component.scss
  src/lib/components/layouts/tag/terra-tag.component.spec.ts
  src/lib/components/layouts/tag/terra-tag.component.ts
Labels: Feature, prettier

#1323 feature(prettier): apply prettier to src/lib/component/layouts/taglist
  src/lib/components/layouts/taglist/example/terra-taglist.component.example.ts
  src/lib/components/layouts/taglist/terra-taglist.component.html
  src/lib/components/layouts/taglist/terra-taglist.component.spec.ts
  src/lib/components/layouts/taglist/terra-taglist.component.ts
Labels: Feature, prettier

#1324 feature(prettier): apply prettier to src/lib/component/loading-spinner
  src/lib/components/loading-spinner/example/terra-loading-spinner.component.example.ts
  src/lib/components/loading-spinner/service/terra-loading-spinner.service.spec.ts
  src/lib/components/loading-spinner/service/terra-loading-spinner.service.ts
  src/lib/components/loading-spinner/terra-loading-spinner.component.scss
  src/lib/components/loading-spinner/terra-loading-spinner.component.ts
Labels: Feature, prettier

#1325 feature(prettier): apply prettier to src/lib/component/no-result
  src/lib/components/no-result/example/terra-no-result-notice.component.example.html
  src/lib/components/no-result/example/terra-no-result-notice.component.example.scss
  src/lib/components/no-result/example/terra-no-result-notice.component.example.ts
  src/lib/components/no-result/terra-no-result-notice.component.html
  src/lib/components/no-result/terra-no-result-notice.component.scss
  src/lib/components/no-result/terra-no-result-notice.component.ts
Labels: Feature, prettier

#1326 feature(prettier): apply prettier to src/lib/component/note
  src/lib/components/note/example/terra-note.component.example.html
  src/lib/components/note/example/terra-note.component.example.ts
  src/lib/components/note/terra-note.component.html
  src/lib/components/note/terra-note.component.scss
  src/lib/components/note/terra-note.component.ts
Labels: Feature, prettier

#1328 enabled tooltips for nodes in category-picker
  CHANGELOG.md
  src/lib/components/data-picker/category-picker/terra-category-picker.component.spec.ts
  src/lib/components/data-picker/category-picker/terra-category-picker.component.ts
  src/lib/components/tree/node-tree/data/terra-node.interface.ts
  src/lib/components/tree/node-tree/node/terra-node.component.html
  src/lib/components/tree/node-tree/node/terra-node.component.spec.ts
  src/lib/components/tree/node-tree/node/terra-node.component.ts
Labels: Fix, Minor change

#1327 feature(prettier): apply prettier to src/lib/component/pager
  src/lib/components/pager/data/terra-pager-default-paging-sizes.ts
  src/lib/components/pager/data/terra-pager.interface.ts
  src/lib/components/pager/data/terra-pager.parameter.interface.ts
  src/lib/components/pager/example/terra-pager.component.example.ts
  src/lib/components/pager/terra-pager.component.html
  src/lib/components/pager/terra-pager.component.scss
  src/lib/components/pager/terra-pager.component.ts
Labels: Feature, prettier

#1332 feature(prettier): apply prettier to src/lib/components/table
  src/lib/components/table/filter.spec.ts
  src/lib/components/table/filter.ts
  src/lib/components/table/has-paginator.interface.ts
  src/lib/components/table/has-sorting.interface.ts
  src/lib/components/table/request-parameter.interface.ts
  src/lib/components/table/table-data-source.spec.ts
  src/lib/components/table/table-data-source.ts
  src/lib/components/table/table-paging-data-source.spec.ts
  src/lib/components/table/table-paging-data-source.ts
  src/lib/components/table/table-paging-sorting-data-source.spec.ts
  src/lib/components/table/table-paging-sorting-data-source.ts
  src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html
  src/lib/components/table/table-settings/dialog/table-settings-dialog.component.spec.ts
  src/lib/components/table/table-settings/dialog/table-settings-dialog.component.ts
  src/lib/components/table/table-settings/dialog/table-settings-dialog.glob.scss
  src/lib/components/table/table-settings/interface/column.interface.ts
  src/lib/components/table/table-settings/interface/table-settings-dialog-data.interface.ts
  src/lib/components/table/table-settings/table-settings.component.html
  src/lib/components/table/table-settings/table-settings.component.spec.ts
  src/lib/components/table/table-settings/table-settings.component.ts
  src/lib/components/table/table-sorting-data-source.spec.ts
  src/lib/components/table/table-sorting-data-source.ts
  src/lib/components/table/terra-mat-paginator-intl.spec.ts
  src/lib/components/table/terra-mat-paginator-intl.ts
Labels: Feature, prettier

#1333 feature(prettier): apply prettier to src/lib/components/tables
  src/lib/components/tables/data-table/context-menu/data/terra-data-table-context-menu-entry.interface.ts
  src/lib/components/tables/data-table/context-menu/example/terra-data-table-context-menu.component.example.ts
  src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.component.html
  src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.component.scss
  src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.component.ts
  src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.directive.ts
  src/lib/components/tables/data-table/context-menu/terra-data-table-context-menu.service.ts
  src/lib/components/tables/data-table/custom-data-table.scss
  src/lib/components/tables/data-table/enums/terra-data-table-sort-order.enum.ts
  src/lib/components/tables/data-table/enums/terra-href-type.enum.ts
  src/lib/components/tables/data-table/enums/terra-text-align.enum.ts
  src/lib/components/tables/data-table/example/data-table-template.component.example.html
  src/lib/components/tables/data-table/example/data-table-template.component.example.ts
  src/lib/components/tables/data-table/example/terra-data-table.component.example.html
  src/lib/components/tables/data-table/example/terra-data-table.component.example.ts
  src/lib/components/tables/data-table/example/terra-data-table.interface.example.ts
  src/lib/components/tables/data-table/example/terra-data-table.service.example.ts
  src/lib/components/tables/data-table/interfaces/terra-data-table-cell.interface.ts
  src/lib/components/tables/data-table/interfaces/terra-data-table-header-cell.interface.ts
  src/lib/components/tables/data-table/interfaces/terra-data-table-row.interface.ts
  src/lib/components/tables/data-table/interfaces/terra-data-table-text.interface.ts
  src/lib/components/tables/data-table/interfaces/terra-href-type.interface.ts
  src/lib/components/tables/data-table/table-row/table-row.component.html
  src/lib/components/tables/data-table/table-row/table-row.component.scss
  src/lib/components/tables/data-table/table-row/table-row.component.spec.ts
  src/lib/components/tables/data-table/table-row/table-row.component.ts
  src/lib/components/tables/data-table/terra-data-table-base.service.spec.ts
  src/lib/components/tables/data-table/terra-data-table-base.service.ts
  src/lib/components/tables/data-table/terra-data-table.component.html
  src/lib/components/tables/data-table/terra-data-table.component.scss
  src/lib/components/tables/data-table/terra-data-table.component.spec.ts
  src/lib/components/tables/data-table/terra-data-table.component.ts
  src/lib/components/tables/fixed-header/fixed-header.directive.ts
  src/lib/components/tables/group-function/example/terra-group-function.component.example.html
  src/lib/components/tables/group-function/example/terra-group-function.component.example.ts
  src/lib/components/tables/group-function/terra-group-function.component.html
  src/lib/components/tables/group-function/terra-group-function.component.scss
  src/lib/components/tables/group-function/terra-group-function.component.spec.ts
  src/lib/components/tables/group-function/terra-group-function.component.ts
  src/lib/components/tables/simple/cell/terra-simple-table-cell.interface.ts
  src/lib/components/tables/simple/cell/terra-simple-table-header-cell.interface.ts
  src/lib/components/tables/simple/example/terra-simple-table.component.example.html
  src/lib/components/tables/simple/example/terra-simple-table.component.example.scss
  src/lib/components/tables/simple/example/terra-simple-table.component.example.ts
  src/lib/components/tables/simple/row/terra-simple-table-row.interface.ts
  src/lib/components/tables/simple/terra-simple-table.component.html
  src/lib/components/tables/simple/terra-simple-table.component.scss
  src/lib/components/tables/simple/terra-simple-table.component.ts
  src/lib/components/tables/terra-base-table.spec.ts
  src/lib/components/tables/terra-base-table.ts
Labels: Feature, prettier

#1334 feature(prettier): apply prettier to src/lib/components/toolbar
  src/lib/components/toolbar/base-toolbar/example/terra-base-toolbar.component.example.html
  src/lib/components/toolbar/base-toolbar/example/terra-base-toolbar.component.example.scss
  src/lib/components/toolbar/base-toolbar/example/terra-base-toolbar.component.example.ts
  src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.glob.scss
  src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.scss
  src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.spec.ts
  src/lib/components/toolbar/base-toolbar/terra-base-toolbar.component.ts
Labels: Feature, prettier

#1335 feature(prettier): apply prettier to src/lib/components/tooltip
  src/lib/components/tooltip/example/tooltip-directive.example.html
  src/lib/components/tooltip/example/tooltip-directive.example.ts
  src/lib/components/tooltip/tooltip.directive.spec.ts
  src/lib/components/tooltip/tooltip.directive.ts
Labels: Feature, prettier

#1336 feature(prettier): apply prettier to src/lib/components/tree
  src/lib/components/tree/base/terra-base-tree.component.ts
  src/lib/components/tree/checkbox-tree/data/terra-checkbox-tree-leaf-state.ts
  src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.html
  src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.scss
  src/lib/components/tree/checkbox-tree/example/terra-checkbox-tree.component.example.ts
  src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.html
  src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.scss
  src/lib/components/tree/checkbox-tree/terra-checkbox-tree.component.ts
  src/lib/components/tree/leaf/terra-checkbox-leaf.interface.ts
  src/lib/components/tree/leaf/terra-leaf.interface.ts
  src/lib/components/tree/node-tree/data/terra-node-tree.config.ts
  src/lib/components/tree/node-tree/data/terra-node.interface.ts
  src/lib/components/tree/node-tree/example/terra-node-tree.component.example.html
  src/lib/components/tree/node-tree/example/terra-node-tree.component.example.ts
  src/lib/components/tree/node-tree/helper/terra-node-tree.helper.ts
  src/lib/components/tree/node-tree/node/terra-node.component.html
  src/lib/components/tree/node-tree/node/terra-node.component.scss
  src/lib/components/tree/node-tree/node/terra-node.component.spec.ts
  src/lib/components/tree/node-tree/node/terra-node.component.ts
  src/lib/components/tree/node-tree/terra-node-tree.component.html
  src/lib/components/tree/node-tree/terra-node-tree.component.scss
  src/lib/components/tree/node-tree/terra-node-tree.component.ts
Labels: Feature, prettier

#1337 feature(prettier): apply prettier to src/lib/components
  src/lib/components/component-collection.ts
  src/lib/components/directive-collection.ts
  src/lib/components/example-collection.ts
Labels: Feature, prettier

#1331 feature(prettier): apply prettier to src/lib/components/stopwatch
  src/lib/components/stopwatch/example/terra-stopwatch.component.example.html
  src/lib/components/stopwatch/example/terra-stopwatch.component.example.ts
  src/lib/components/stopwatch/terra-stopwatch.component.html
  src/lib/components/stopwatch/terra-stopwatch.component.spec.ts
  src/lib/components/stopwatch/terra-stopwatch.component.ts
Labels: Feature, prettier

#1338 feature(prettier): apply prettier to other files
  .github/workflows/ci.yml
  src/assets/lang/locale-de.json
  src/assets/lang/locale-en.json
  src/index.html
  src/lib/components/data-picker/category-picker/terra-category-picker.component.spec.ts
  src/lib/components/editors/code-editor/terra-code-editor.component.ts
  src/lib/components/forms/input/time-picker/terra-time-picker.component.spec.ts
  src/lib/components/forms/input/time-picker/terra-time-picker.component.ts
  src/lib/components/forms/slider/data/terra-slider-tick.spec.ts
  src/lib/components/tables/data-table/terra-data-table.component.ts
  src/lib/helpers/sort.helper.ts
  src/lib/helpers/tests/query-param.helper.spec.ts
  src/lib/helpers/tests/sort.helper.spec.ts
  src/lib/helpers/tests/url.helper.spec.ts
  src/lib/package.json
  src/lib/pipes/pipe-collection.ts
  src/lib/pipes/select-sort.pipe.spec.ts
  src/lib/pipes/select-sort.pipe.ts
  src/lib/public-api.ts
  src/lib/schematics/collection.json
  src/lib/schematics/migration.json
  src/lib/schematics/ng-add/index.ts
  src/lib/schematics/ng-update/checkbox-migration/index.ts
  src/lib/schematics/ng-update/checkbox-migration/schema.json
  src/lib/schematics/ng-update/checkbox-migration/schema.ts
  src/lib/schematics/utils/compiler-hosts.ts
  src/lib/styles/material/_checkbox.scss
  src/lib/styles/material/_table.scss
  src/lib/styles/styles.scss
  src/lib/terra-components-examples.module.ts
  src/lib/terra-components.module.ts
  src/lib/testing/mock-translation-service.ts
  src/lib/tsconfig.lib.json
  src/lib/tsconfig.schematics.json
  src/lib/tsconfig.spec.json
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/test.ts
  src/tsconfig.app.json
Labels: Feature, prettier

#1339 feature(prettier): finalizing work
  CHANGELOG.md
  package.json
  src/lib/components/forms/dynamic-form/service/terra-json-to-form-field.service.ts
  tslint.json
Labels: Feature, prettier

#1329 fix(deps / security vulnerability): terser-webpack-plugin
  package-lock.json
Labels: Fix, Patch

#1341 feature(prettier): fix pre-commit hook
  README.md
  angular.json
  package-lock.json
  package.json
Labels: Feature, prettier

#1342 fix(deps): npm update dot-prop --depth 4
  package-lock.json
Labels: Fix, security vulnerability, v5
