Repository plentymarkets/terra-components, pull requests merged in 2020-01, with the labels that each got.

#1111 fix: add FilterComponent to public api
  src/lib/public-api.ts
Labels: Fix

#1102 fix(http-interceptors): add dependencies to the providers to make them actually work
  CHANGELOG.md
  src/lib/http-interceptors/index.ts
Labels: Fix, Patch, v4

#1117 fix(form): consistent data handling #1 - form value includes the value of a hidden form field
  CHANGELOG.md
  src/lib/components/forms/form/example/form-fields.ts
  src/lib/components/forms/form/example/terra-form.component.example.html
  src/lib/components/forms/form/example/terra-form.component.example.ts
  src/lib/components/forms/form/form-container/terra-form-container.component.ts
Labels: Fix

#1120 feature(file-browser): use HttpClient instead of TerraBaseService
  CHANGELOG.md
  src/lib/components/file-browser/terra-base-storage.interface.ts
  src/lib/components/file-browser/terra-frontend-storage.service.ts
Labels: Feature

#1118 remove split view
  CHANGELOG.md
  src/lib/components/component-collection.ts
  src/lib/components/dynamic-module-loader/data/terra-dynamic-loaded-component-input.interface.ts
  src/lib/components/dynamic-module-loader/data/terra-split-view-component.interface.ts
  src/lib/components/dynamic-module-loader/terra-dynamic-module-loader.component.html
  src/lib/components/dynamic-module-loader/terra-dynamic-module-loader.component.scss
  src/lib/components/dynamic-module-loader/terra-dynamic-module-loader.component.ts
  src/lib/components/split-view/multi/helpers/terra-multi-split-view.helper.ts
  src/lib/components/split-view/multi/helpers/terra-resolved-data.helper.ts
  src/lib/components/split-view/multi/injectables/terra-multi-split-view-breadcrumbs.service.ts
  src/lib/components/split-view/multi/injectables/terra-multi-split-view.config.ts
  src/lib/components/split-view/multi/interfaces/resolve-list-item.interface.ts
  src/lib/components/split-view/multi/interfaces/resolved-data.interface.ts
  src/lib/components/split-view/multi/interfaces/terra-multi-split-view-module.interface.ts
  src/lib/components/split-view/multi/interfaces/terra-multi-split-view-route-data.interface.ts
  src/lib/components/split-view/multi/interfaces/terra-multi-split-view-route.interface.ts
  src/lib/components/split-view/multi/interfaces/terra-multi-split-view-routes.ts
  src/lib/components/split-view/multi/interfaces/terra-multi-split-view.interface.ts
  src/lib/components/split-view/multi/terra-multi-split-view.component.glob.scss
  src/lib/components/split-view/multi/terra-multi-split-view.component.html
  src/lib/components/split-view/multi/terra-multi-split-view.component.scss
  src/lib/components/split-view/multi/terra-multi-split-view.component.spec.ts
  src/lib/components/split-view/multi/terra-multi-split-view.component.ts
  src/lib/public-api.ts
  src/lib/styles/styles.scss
Labels: Feature, Major change

#1121 remove terra base service
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/components/forms/dynamic-form/service/terra-dynamic-form.service.ts
  src/lib/components/forms/input/file-input/terra-file-input.component.spec.ts
  src/lib/components/forms/suggestion-box/terra-suggestion-box.component.spec.ts
  src/lib/components/stopwatch/terra-stopwatch.component.spec.ts
  src/lib/components/tables/data-table/terra-data-table.component.spec.ts
  src/lib/package.json
  src/lib/service/data/terra-query-encoder.ts
  src/lib/service/index.ts
  src/lib/service/terra-base.service.ts
  src/lib/terra-components.module.ts
Labels: Feature, Major change
