Repository plentymarkets/terra-components, pull requests merged in 2020-09, with the labels that each got.

#1345 proper styling & highlighting for links in alert boxes
  src/lib/styles/styles.scss
Labels: Feature, Patch, prettier, v5

#1349 Update _table.scss
  CHANGELOG.md
  src/lib/styles/material/_table.scss
Labels: Fix, Patch

#1350 change l10n
  CHANGELOG.md
  src/assets/lang/locale-de.json
  src/assets/lang/locale-en.json
  src/lib/components/table/table-settings/dialog/table-settings-dialog.component.html
  src/lib/components/table/table-settings/table-settings.component.html
Labels: Fix, Patch

#1351 feature(prettier): improve usage of prettier
  .github/workflows/ci.yml
  .prettierrc.js
  package-lock.json
  package.json
Labels: prettier
