Repository plentymarkets/terra-components, pull requests merged in 2020-05, with the labels that each got.

#1193 feature(deps): update semver
  package-lock.json
  package.json
Labels: dependencies

#1211 fix(form-field-styles): add ng-touched to ng-invalid
  CHANGELOG.md
  src/lib/styles/material/_form-field.scss
Labels: Fix

#1200 feature(table): add data sources for mat-table
  CHANGELOG.md
  src/lib/components/table/filter.spec.ts
  src/lib/components/table/filter.ts
  src/lib/components/table/has-paginator.interface.ts
  src/lib/components/table/has-sorting.interface.ts
  src/lib/components/table/index.ts
  src/lib/components/table/request-parameter.interface.ts
  src/lib/components/table/table-data-source.spec.ts
  src/lib/components/table/table-data-source.ts
  src/lib/components/table/table-paging-data-source.spec.ts
  src/lib/components/table/table-paging-data-source.ts
  src/lib/components/table/table-paging-sorting-data-source.spec.ts
  src/lib/components/table/table-paging-sorting-data-source.ts
  src/lib/components/table/table-sorting-data-source.spec.ts
  src/lib/components/table/table-sorting-data-source.ts
  src/lib/public-api.ts
  src/lib/service/index.ts
  src/lib/testing/mock-change-detector-ref.ts
Labels: Minor change

#1198 feature(prettier): apply prettier to src/app
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/showcase/showcase.component.html
  src/app/showcase/showcase.component.scss
  src/app/showcase/showcase.component.ts
  src/app/translation/l10n.config.ts
Labels: Feature, prettier

#1208 feature(prettier): apply prettier to src/assets
  src/assets/lang/locale-de.json
  src/assets/lang/locale-en.json
Labels: Feature, prettier
