Repository plentymarkets/terra-components, pull requests merged in 2020-06, with the labels that each got.

#1213 feature (mat-checkbox): add new styles
  CHANGELOG.md
  src/app/app.module.ts
  src/lib/styles/material/_checkbox.scss
  src/lib/styles/material/_table.scss
  src/lib/styles/styles.scss
Labels: Feature

#1209 feature(prettier) apply prettier to src/lib/environment
  src/lib/environments/environment.test.ts
  src/lib/environments/environment.ts
Labels: Feature, prettier

#1210 feature(prettier): apply prettier to src/lib/helpers
  src/lib/helpers/activated-route.helper.ts
  src/lib/helpers/clipboard.helper.ts
  src/lib/helpers/dispatch.helper.ts
  src/lib/helpers/download.helper.ts
  src/lib/helpers/enums/button-color.enum.ts
  src/lib/helpers/enums/indicator-label-type.enum.ts
  src/lib/helpers/enums/terra-placement.enum.ts
  src/lib/helpers/fileType.helper.ts
  src/lib/helpers/number.helper.ts
  src/lib/helpers/object.helper.ts
  src/lib/helpers/path.helper.ts
  src/lib/helpers/query-param.helper.ts
  src/lib/helpers/regex/terra-regex.ts
  src/lib/helpers/string.helper.ts
  src/lib/helpers/terra-converter.helper.ts
  src/lib/helpers/terra-label-tooltip.directive.ts
  src/lib/helpers/terra-pdf.helper.ts
  src/lib/helpers/tests/number.helper.spec.ts
  src/lib/helpers/tests/path.helper.spec.ts
  src/lib/helpers/tests/string.helper.spec.ts
  src/lib/helpers/two-column.helper.ts
  src/lib/helpers/url.helper.ts
Labels: Feature, prettier

#1229 feature(prettier): apply prettier to src/lib/styles
  src/lib/styles/_variables.scss
  src/lib/styles/fonts/fonts.glob.scss
  src/lib/styles/fonts/plentyicons.scss
  src/lib/styles/fonts/plentysans.scss
  src/lib/styles/iconDescription.json
  src/lib/styles/icons.scss
  src/lib/styles/material/_checkbox.scss
  src/lib/styles/material/_dialog.scss
  src/lib/styles/material/_form-field.scss
  src/lib/styles/material/_tab.scss
  src/lib/styles/material/_table.scss
  src/lib/styles/material/_toggle.scss
  src/lib/styles/styles.scss
  src/lib/styles/themes/theme-compact.scss
  src/lib/styles/themes/theme-core.scss
  src/lib/styles/themes/theme-dark.scss
  src/lib/styles/themes/theme-filled-buttons.scss
  src/lib/styles/themes/theme-light.scss
  src/lib/styles/themes/theme-loader.scss
  src/lib/styles/themes/theme-xmas.scss
Labels: Feature, prettier

#1231 feature(prettier): apply prettier to src/lib/utils
  src/lib/utils/http-param-encoder.ts
  src/lib/utils/http-params.spec.ts
  src/lib/utils/http-params.ts
  src/lib/utils/window.ts
Labels: Feature, prettier

#1232 feature(prettier): apply prettier to src/lib/validators
  src/lib/validators/iban-validator.spec.ts
  src/lib/validators/iban-validator.ts
  src/lib/validators/terra-decimal-validator.ts
  src/lib/validators/unique-values-validator.spec.ts
  src/lib/validators/unique-values-validator.ts
  src/lib/validators/validators.spec.ts
  src/lib/validators/validators.ts
Labels: Feature, prettier

#1218 feature(prettier): apply prettier to src/lib/service
  src/lib/service/data/exception.interface.ts
  src/lib/service/index.ts
  src/lib/service/model-cache.ts
Labels: Feature, prettier

#1217 feature(prettier): apply prettier to src/lib/models
  src/lib/models/terra-key-value-pair.interface.ts
  src/lib/models/terra-key-value.interface.ts
Labels: Feature, prettier

#1216 feature(prettier) apply prettier to src/lib/http-interceptors
  src/lib/http-interceptors/auth.interceptor.spec.ts
  src/lib/http-interceptors/auth.interceptor.ts
  src/lib/http-interceptors/error.interceptor.spec.ts
  src/lib/http-interceptors/error.interceptor.ts
  src/lib/http-interceptors/interceptor-providers.ts
  src/lib/http-interceptors/loading.interceptor.spec.ts
  src/lib/http-interceptors/loading.interceptor.ts
Labels: Feature, prettier

#1230 feature(prettier): apply prettier to src/lib/testing
  src/lib/testing/file-input/file-data.ts
  src/lib/testing/file-input/terra-frontend-storage-service-stub.ts
  src/lib/testing/mock-activated-route.ts
  src/lib/testing/mock-buttons.ts
  src/lib/testing/mock-change-detector-ref.ts
  src/lib/testing/mock-element-ref.ts
  src/lib/testing/mock-router.ts
  src/lib/testing/mock-tags.ts
  src/lib/testing/mock-translation-module.ts
  src/lib/testing/mock-translation-service.ts
Labels: Feature, prettier

#1214 feature(deps): update karma, jasmine and all of their dependent packages
  package-lock.json
  package.json
  src/lib/components/table/table-data-source.spec.ts
Labels: dependencies

#1192 feature(deps): update gulp-sass to resolve security vulnerability
  package-lock.json
  package.json
Labels: dependencies

#1251 fix(deps): updated http-proxy to v1.18.1 to resolve security vulnerability
  package-lock.json
Labels: Fix, dependencies, security vulnerability

#1206 feature(schematics): support "ng add"
  .travis.yml
  CHANGELOG.md
  package.json
  src/lib/package.json
  src/lib/schematics/collection.json
  src/lib/schematics/ng-add/index.ts
  src/lib/tsconfig.schematics.json
Labels: Feature, Minor change

#1246 Feature/mat sort
  CHANGELOG.md
  src/lib/components/directive-collection.ts
  src/lib/components/forms/select-box/directive/select-sort.directive.spec.ts
  src/lib/components/forms/select-box/directive/select-sort.directive.ts
  src/lib/helpers/index.ts
  src/lib/helpers/sort.helper.ts
  src/lib/helpers/tests/sort.helper.spec.ts
  src/lib/pipes/pipe-collection.ts
  src/lib/pipes/select-sort.pipe.spec.ts
  src/lib/pipes/select-sort.pipe.ts
  src/lib/public-api.ts
  src/lib/terra-components.module.ts
Labels: Feature, Minor change

#1195 feature(deps): update iban
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/package.json
Labels: dependencies
